FROM alpine:latest AS prep
RUN apk --update add ca-certificates

FROM scratch

ARG USER_UID=10001
ARG USER_GID=10001
USER ${USER_UID}:${USER_GID}

COPY --from=prep /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY dist/otelcol-contrib-candid /otelcol-contrib-candid
EXPOSE 19418
ENTRYPOINT ["/otelcol-contrib-candid"]
